### ISSUE TITLE
Computation of TaskName overly complicated

### ISSUE THREAD

**Issue by StephanErb** [wndhydrnt/mesos-task-exporter#3]
It seems like that the way you compute the name of a task is overly complicated. As far as I know, most framework set it as `source` in `monitor/statistics.json`. 

For example, the mesos_exporter also uses the `source` attribute to derive the task name:  https://github.com/prometheus/mesos_exporter/blob/master/main.go#L166

**Comment by wndhydrnt** [comment]
The motivation behind reading the name of the task from the Mesos master is to get a human-readable name to make querying in the UI of Prometheus easier.

For example, the value of `source` of a task scheduled by Marathon looks like `group_service_redis.ccede1f8-24c4-11e5-84ae-56847afe9799`, which is kind of ok to use when writing a Prometheus query. The `source` of a task scheduled by Chronos looks like `ct:1436289360000:0:dockerjob:`. `ChronosTask:dockerjob` is just easier to read and is also consistent between several runs of a job. Imagine the job on Chronos running every five minutes.

What is your concern regarding the way this is handled? Do you see any performance issues or other things?

**Comment by StephanErb** [comment]
I wasn't aware that these framework inject UUIDs into the source attribute. We can close this issue as invalid. Sorry for the fuss :-)
